[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false


[[redirects]]
  from = "/111"
  to = "https://afflat3d2.com/lnk.asp?o=9851&c=918277&a=403969&k=2AF1F0DA954B3F0181EC9FB7F58B9B85&l=9540"
  status = 301
  force = true
  
  [[redirects]]
  from = "/"
  to = "https://afflat3d2.com/lnk.asp?o=16383&c=918277&a=403969&k=FA59AC980EAB399FC94C42291FE31251&l=17609"
  status = 301
  force = true
  
  [[redirects]]
  from = "/1/"
  to = "https://afflat3d2.com/lnk.asp?o=16383&c=918277&a=403969&k=FA59AC980EAB399FC94C42291FE31251&l=17609"
  status = 301
  force = true

  [[redirects]]
  from = "/2/"
  to = "https://afflat3d2.com/lnk.asp?o=16650&c=918271&a=403969&k=28C94FD96C04C7295F03CA7C80DECAB9&l=17814"
  status = 301
  force = true
  
  [[redirects]]
  from = "/3/"
  to = "https://warriorplus.com/o2/a/gb7g94/0"
  status = 301
  force = true

  [[redirects]]
  from = "/4/"
  to = "https://brixxs.com/"
  status = 301
  force = true

  [[redirects]]
  from = "/remote-work/"
  to = "https://afflat3d2.com/lnk.asp?o=15647&c=918277&a=403969&k=B2DCB7B5F106CF050CCEEA4FEFF916A5&l=16862"
  status = 301
  force = true
